version: '3.5'

services:

  php:
    build: docker/php
    ports:
    - 80:80
    volumes:
    - ./:/var/www/html
    - ./app:/var/www//app/
    - ./.env:/var/www//.env/

  mysql:
    image: mysql:latest
    ports:
    - 8889:8889
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./databases/mysql:/var/lib/mysql

  adminer:
    image: adminer:latest
    restart: always
    ports: 
    - 8080:8080