name: PHP Fixer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: apply fixer
      run: vendor/bin/php-cs-fixer fix --config .php-cs-fixer.php
